# Introduction to Python

## Numpy

## Metodos Computacionales 1
## Uniandes

Based on [SoloLearn Python](https://www.sololearn.com/Play/Python)

## Numpy Arrays

In [1]:
import numpy as np

In [2]:
# Creating a numpy array
a = np.array([[1,2,3,4],[5,6,7,8]])

a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
# Selecting an element in two diferent ways
print(a[0][1])
print(a[0, 1])

2
2


In [4]:
# Attributes of a numpy array
print(a.ndim)
print(a.shape)
print(a.size)
print(type(a))

2
(2, 4)
8
<class 'numpy.ndarray'>


## Initializing a numpy array

In [5]:
# Array of ones
b = np.ones((2,3))

b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# Array of zeros
c = np.zeros((2,4))

c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
h = np.full((2,4), 3)
h

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [8]:
# Array of random numbers
d = np.random.random((2,4))

d

array([[0.80338489, 0.46009793, 0.70187682, 0.18828094],
       [0.33066254, 0.8655148 , 0.93050914, 0.2131253 ]])

In [9]:
# Identity matrix
#g = np.eye(4)
g = np.identity(4)
g

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Creating ranges in numpy arrays

In [10]:
l = range(10)
print([i for i in range(10)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
# numpy range
j = np.arange(10)
print(j)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# numpy range
i = np.arange(0,10,2)
print(i)

[0 2 4 6 8]


In [13]:
# Creating a list with numbers in between
k= np.linspace(0,10,36)
print(k)

[ 0.          0.28571429  0.57142857  0.85714286  1.14285714  1.42857143
  1.71428571  2.          2.28571429  2.57142857  2.85714286  3.14285714
  3.42857143  3.71428571  4.          4.28571429  4.57142857  4.85714286
  5.14285714  5.42857143  5.71428571  6.          6.28571429  6.57142857
  6.85714286  7.14285714  7.42857143  7.71428571  8.          8.28571429
  8.57142857  8.85714286  9.14285714  9.42857143  9.71428571 10.        ]


## Utils Functions

In [14]:
# Reshaping a matrix
l = np.array([[1,2,3],[4,5,6]])
print(l)
print(l.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


## Slicing numpy arrays

In [15]:
# Create an array
m = np.arange(8)
print(m)
# Slicing
n = m[::-1]
print(n)
o = m[:5]
print(o)
p = m[6:]
print(p)

[0 1 2 3 4 5 6 7]
[7 6 5 4 3 2 1 0]
[0 1 2 3 4]
[6 7]


In [16]:
# Changing a value of the array
m[4] = 100
print(m)

[  0   1   2   3 100   5   6   7]


In [17]:
# Multidimensional slicing
q = np.array([[10,11,12,13],[20,22,23,25]])
print(q)
# # Select some elements
#print(q[0:1,1])
# Select a column
# print(q[:,0])
# # Select a row
print(q[1,:])

[[10 11 12 13]
 [20 22 23 25]]
[20 22 23 25]


In [18]:
# Slicing with condition
rango = np.arange(10)
squares = np.arange(10)**2
print(squares[rango < 5])

[ 0  1  4  9 16]


## Arithmetic Operations

In [19]:
x = np.array([[1,2,3,4],[5,6,7,8]])
y = np.array([[9,10,11,12],[13,14,15,16]])

In [20]:
# Add two matrices
z = x + y
print(z)

[[10 12 14 16]
 [18 20 22 24]]


In [21]:
# Numpy functions
a = np.exp(x)
print(a)
b = np.sqrt(x)
print(b)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]


In [22]:
# Matrix multiplication, the shapes do not align for matrix multiplication
c = np.dot(x, y)
print(c)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [23]:
# Matrix multiplication
c = np.dot(x, y.T)
print(c)

[[110 150]
 [278 382]]


In [24]:
# Matrix multiplication
print(x @ y.T)

[[110 150]
 [278 382]]


In [25]:
# Norm of a vector
x = np.arange(10)
print(np.linalg.norm(x))

16.881943016134134


## Axis operations

In [26]:
A = np.random.randint(0, 6, (2, 3))
print(A)
print(A.sum())
print(A.sum(axis = 0))
print(A.sum(axis = 1))

[[4 4 5]
 [3 3 2]]
21
[7 7 7]
[13  8]
